### ISSUE TITLE
Js syntax error

### ISSUE THREAD

**Issue by jobinli** [inocturne/hyperf-chat#1]
![image](https://user-images.githubusercontent.com/59111601/82855620-5b7e1600-9f3e-11ea-9590-c0d44660ef40.png)

this should be the syntax of PHP?

**Comment by AuroraYolo** [comment]
你这个是浏览器的错误吗？

**Comment by jobinli** [comment]
从 chrome 79.* 升级到了 83.* 这个错误就没有了。不过我觉得，前端还是采取兼容性较好的写法比较好。

**Comment by AuroraYolo** [comment]
这个是layui js里的代码，我没有修改过里面的代码
