### ISSUE TITLE
这边通过websocket给服务器发消息，但是貌似没有给每一条消息定一个唯一的标记。

### ISSUE THREAD

**Issue by luoyou** [inocturne/hyperf-chat#3]
https://github.com/komorebi-php/hyperf-chat/blob/bf46cbfd3a0503663639bf46c9733ab972620559/app/Controller/Ws/WebSocketController.php#L53

假设某个接口，会返回用户查看的次数，那么用户反复查看，可能会导致websocket返回的不是最新的数据。

**Comment by AuroraYolo** [comment]
有message_id
